CREATE TABLE `raaj_COMMENTS` (
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`USERNAME` VARCHAR(50) NOT NULL, 
	`TASK_ID` INT(10) NOT NULL, 
	`COMMENT` LONGTEXT NOT NULL, 
	`DATE` DATETIME NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;